# all processes will read configuration from here (maybe, haven't decided yet)

use_gpu: false
train:
  learning_rate: 0.001
  # epochs: 5
  data:
    # dataset: "imbd"
    path_to_slice: "./pipelines/slice.safetensors"
    # slices: 5
    batch_size: 32
model:
  attention_kind: "Quadratic"
  dimension: 32
  depth: 1
  heads: 2
  context_window: 300
  input_vocabolary: 60000
  output_vocabolary: 5










