# .github/workflows/build.yml
name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pytorch
        run: pip install torch==2.2.0
      - name: Find and set torch lib path
        run: |
          SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
          TORCH_LIB_PATH="${SITE_PACKAGES}/torch/lib"
          echo "LD_LIBRARY_PATH=$TORCH_LIB_PATH" >> $GITHUB_ENV
          echo "LIBTORCH_USE_PYTORCH=1" >> $GITHUB_ENV
          echo "RUST_BACKTRACE=full" >> $GITHUB_ENV
      - run: echo $RUST_BACKTRACE
      - name: Compile
        id: compile
        run: cargo build --release --target-dir build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: build/release/llm-voice-chat
