# .github/workflows/build.yml
name: "Training Loop: Build Rust Binary"

on:
  workflow_dispatch:


jobs:
  
  build:
    name: Build
    runs-on: self-hosted
    container:
      image: ghcr.io/digital-defiance/sentiment-analysis-pipeline:main
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
    
      - name: Find and set torch lib path
        run: |
          SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
          TORCH_LIB_PATH="${SITE_PACKAGES}/torch/lib"
          echo "LD_LIBRARY_PATH=$TORCH_LIB_PATH" >> $GITHUB_ENV
          echo "LIBTORCH_USE_PYTORCH=1" >> $GITHUB_ENV
          echo "RUST_BACKTRACE=full" >> $GITHUB_ENV
      - run: echo $RUST_BACKTRACE
      - name: Compile
        run: cargo build --release --target-dir build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: llm-voice-chat
          path: build/release/llm-voice-chat
