name: Create experiment from PR

on:
  pull_request:
    types: [opened]

jobs:
  create-experiment:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'experiment:')
    container:
      image: ghcr.io/digital-defiance/mlflow:main
      env:
        MLFLOW_BACKEND_STORE_URI: ${{ secrets.DB_URI }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MLFLOW_ARTIFACTS_DESTINATION: s3://digitaldefiancemlartifacts
    steps:
    - name: Create experiment
      shell: python
      run: |
        from mlflow import MlflowClient
        client = MlflowClient(tracking_uri="${{ secrets.DB_URI }}")
        experiment_name = "${{ github.event.pull_request.title }}"
        experiment_name = experiment_name[11:]
        experiment_id = client.create_experiment(
            "${{ github.event.pull_request.number }}:" + experiment_name,
            artifact_location="s3://digitaldefiancemlartifacts",
            tags={
              "pr_number": "${{ github.event.pull_request.number }}",
              "description": "${{ github.event.pull_request.number }}",
            },
        )
        experiment = client.get_experiment(experiment_id)
        print(f"Name: {experiment.name}")
        print(f"Experiment_id: {experiment.experiment_id}")
        print(f"Artifact Location: {experiment.artifact_location}")
        print(f"Tags: {experiment.tags}")
        print(f"Lifecycle_stage: {experiment.lifecycle_stage}")
        print(f"Creation timestamp: {experiment.creation_time}")

        with open("experiment_id.txt", "w") as file:
            file.write(experiment_id)
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pr-${{ github.event.pull_request.number }}
        path: experiment_id.txt

