name: Create experimen on PR

on:
  pull_request:
    types: [opened]

jobs:
  append-info:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'experiment:')
    container:
      image: ghcr.io/digital-defiance/mlflow:main
      env:
        MLFLOW_BACKEND_STORE_URI: ${{ secrets.DB_URI }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MLFLOW_ARTIFACTS_DESTINATION: s3://digitaldefiancemlartifacts
    steps:
    - name: Create experiment
      shell: python
      run: |
        import mlflow
        
      
 
