
# .github/workflows/build.yml
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r pipelines/requirements.txt
      - name: Deploy sentiment analysis flow
        run: python pipelines/deploy.py

