
# .github/workflows/build.yml
name: Deploy sentiment analysis flow

on:
  workflow_dispatch:
  push:

jobs:
  deploy-sentiment-analysis-flow:
    name: Deploy flow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install torch==2.2.0 pydantic duckdb prefect numpy pydantic-settings safetensors tiktoken
      - name: Login to prefect
        run: prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace 'digital-defiance/default'
      - name: Deploy sentiment analysis flow
        run: python pipelines/deploy.py

