name: "Development Environment: Deploy Remote VScode"

on:
  workflow_dispatch:


jobs:
  deploy-dev-env:
    runs-on: self-hosted
    container:
      image: gitpod/workspace-rust
      options: --user root
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup code CLI
        run: |
          curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
          tar -xf vscode_cli.tar.gz

      - name: Start VSCode CLient
        run: ./code tunnel
