name: "MLFlow: Deploy"

on:
  workflow_dispatch:

jobs:
  deploy-mlflow:
    name: Deploy development environment
    runs-on: mlflow
    container:
      image: traefik:v2.4
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
        - 80:80
  
    services:
      mlflow:
        image: ghcr.io/mlflow/mlflow
        options: |
          --label "traefik.enable=true"
          --label "traefik.http.routers.mlflow.rule=PathPrefix(`/`)"
          --label "traefik.http.services.mlflow.loadbalancer.server.port=5000"
          --label "traefik.http.routers.mlflow.entrypoints=mlflow"
          --label "traefik.http.middlewares.mlflow-auth.basicauth.users=${{ secrets.MLFLOW_USERNAME }}:${{ secrets.MLFLOW_PASSWORD }}"
          --label "traefik.http.routers.mlflow.middlewares=mlflow-auth"
        env:
          AWS_REGION: eu-south-1
          MLFLOW_BACKEND_STORE_URI: ${{ secrets.DB_URI }}
          MLFLOW_HOST: 0.0.0.0
          MLFLOW_PORT: 80
          MLFLOW_WORKERS: 2
  
    steps:
      - name: Hook
        timeout-minutes: 9999999999999999
        run: |
          traefik --label "traefik.enable=true"
            --label "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
            --label "traefik.http.services.traefik.loadbalancer.server.port=8080"
            --label "traefik.http.routers.traefik.entrypoints=web"
    
