name: "MLFlow: Deploy"

on:
  workflow_dispatch:
    inputs:
      machine:
        description: 'Which machine to use'
        required: true
        default: 'mlflow'
        type: choice
        options:
          - mlflow
          - local

jobs:
  deploy-mlflow:
    name: Deploy MLFlow
    runs-on: ${{ inputs.machine }}
    steps:
      - run: pip install boto3
      - name: Setup auth config
        shell: python
        run: |
          with open("${{ github.workspace }}/auth.ini", "w") as file:
            file.write("""
          [mlflow]
          admin_username = ${{ secrets.MLFLOW_USERNAME }}
          admin_password = ${{ secrets.MLFLOW_PASSWORD }}
          default_permission = READ
          database_uri = sqlite:///sqlite.db
            """)
      - name: Run server
        timeout-minutes: 720
        run: MLFLOW_AUTH_CONFIG_PATH="${{ github.workspace }}/auth.ini" python -m mlflow server --app-name basic-auth --host 0.0.0.0 --port 8000 --workers 2 --backend-store-uri ${{ secrets.DB_URI }}
    
