name: "MLFlow: Deploy"

on:
  workflow_dispatch:

jobs:
  deploy-mlflow:
    name: Deploy development environment
    runs-on: mlflow
    steps:
      - name: Serve MLFlow
        timeout-minutes: 9999999999999999
        env:
          AWS_REGION: eu-south-1
          MLFLOW_BACKEND_STORE_URI: ${{ secrets.DB_URI }}
          MLFLOW_HOST: 0.0.0.0
          MLFLOW_PORT: 80
          MLFLOW_WORKERS: 2
        run: python -m mlflow server
    
