name: "MLFlow: Deploy"

on:
  workflow_dispatch:

jobs:
  deploy-mlflow:
    name: Deploy development environment
    runs-on: mlflow
    env:
      AWS_REGION: eu-south-1
      MLFLOW_BACKEND_STORE_URI: ${{ secrets.DB_URI }}
      MLFLOW_HOST: 0.0.0.0
      MLFLOW_PORT: 80
      MLFLOW_WORKERS: 2
  
    steps:
      - name: Setup auth config
        shell: python
        run: |
          with open("auth.ini") as file:
            file.write("""
            
            
            """)
      - name: Run server
        timeout-minutes: 9999999999999999
        run: mlflow server
    
