name: "MLFlow: Deploy"

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-south-1
  MLFLOW_BACKEND_STORE_URI: ${{ secrets.DB_URI }}
  MLFLOW_HOST: 0.0.0.0
  MLFLOW_PORT: 80
  MLFLOW_WORKERS: 2

jobs:
  deploy-mlflow:
    name: Deploy development environment
    runs-on: mlflow
    steps:
      - name: Setup Credentials
        shell: python
        run: |
          with open("credentials", "w") as file:
            file.write(f"""
          [mlflow]
          username = ${{ secrets.MLFLOW_USERNAME }}
          password = ${{ secrets.MLFLOW_PASSWORD }}
            """)
          
      - name: Serve MLFlow
        timeout-minutes: 999999999999 
        run: |
          python -m mlflow server --workers 2 --host 0.0.0.0 --port 80
    
