name: "MLFlow: Deploy"

on:
  workflow_dispatch:

jobs:
  deploy-mlflow:
    name: Deploy MLFlow
    runs-on: mlflow
    steps:
      - name: Setup auth config
        shell: python
        run: |
          with open("${{ github.workspace }}/auth.ini", "w") as file:
            file.write("""
          [mlflow]
          username = ${{ secrets.MLFLOW_USERNAME }}
          password = ${{ secrets.MLFLOW_PASSWORD }}
            """)
      - name: Run server
        timeout-minutes: 9999999999999999
        run: MLFLOW_AUTH_CONFIG_PATH="${{ github.workspace }}/auth.ini" python -m mlflow server --app-name basic-auth --host 0.0.0.0 --port 8000 --workers 2 --backend-store-uri ${{ secrets.DB_URI }}
    
