
name: Test Workflow to Setup Self Hosted Runners

on:
  workflow_dispatch:
  
  

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and load Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./.devcontainer
        push: false
        tags: devcontainer
        load: true

  test:
    needs: build
    container:
      image: devcontainer
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        echo "success"

