name: Test Workflow with GitHub Container Registry

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./.devcontainer
        push: true
        tags: ghcr.io/${{ github.event.repository.name | lower }}/devcontainer:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.event.repository.name | lower }}/devcontainer:latest
    steps:
    - name: Test
      run: |
        echo "success"
