name: GPT Array Sorter Experiment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Loss Function'
        required: true
        default: 'CrossEntropy'
        type: choice
        options:
          - 'CrossEntropy'

      number_of_blocks:
        description: 'The number of transformer blocks.'
        required: true
        type: string
      coordinates:
        description: 'The word embedding dimension.'
        required: true
        type: string
      words:
        description: 'The number of tokens in the input sequence.'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install awscli boto3
        pip install -r .devcontainer/requirements.txt

    - name: Babysit Experiment
      run: |
        cd gpt_array_sorter
        python train_main.py