name: Test Workflow with GitHub Container Registry

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase repo name
      id: set_env
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./.devcontainer
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}/devcontainer:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/${{ env.REPO_NAME }}/devcontainer:latest
    steps:
    - name: Test
      run: |
        echo "success"
