
name: "Sentiment Analysis: Deploy Pipeline"

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: digital-defiance/sentiment-analysis-pipeline

jobs:
  deploy-sentiment-analysis-flow:
    name: Deploy flow
    runs-on: self-hosted
    container:
      image: ghcr.io/digital-defiance/sentiment-analysis-pipeline:main
    steps:
      - uses: actions/checkout@master
      - name: Login to prefect
        run: yes | prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace 'digital-defiance/default'
      - run: ls
      - name: Deploy sentiment analysis flow
        run: python pipelines/sentiment_analysis/deploy.py
