name: Start Experiment

on:
  pull_request:
    types: [closed]

jobs:
  trigger-sentiment-analysis-task-asa:
    name: Start experiment
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'experiment:')
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/digital-defiance/mlflow:main
      env:
        MLFLOW_BACKEND_STORE_URI: ${{ secrets.DB_URI }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        MLFLOW_ARTIFACTS_DESTINATION: s3://digitaldefiancemlartifacts
    steps:
      - name: Get experiment id and dispatch workflow
        shell: python
        id: get_experiment_id
        run: |
          from mlflow import MlflowClient
          import requests
          import json

          client = MlflowClient(tracking_uri="${{ secrets.DB_URI }}")
          experiment_name = "${{ github.event.pull_request.title }}"
          experiment_name = experiment_name[11:]
          experiment_name = "${{ github.event.pull_request.number }}:" + experiment_name
          experiment = client.get_experiment_by_name(experiment_name)

          response = requests.post(
              'https://api.github.com/repos/${{ github.repository }}/actions/workflows/train-model-sentiment-analysis-task-asa.yml/dispatches',
              headers={
                  'Authorization': 'token ${{ secrets.PERSONAL_ACCESS_TOKEN }}',
                  'Accept': 'application/vnd.github.v3+json',
              },
              data=json.dumps({
                  'ref': 'main',
                  'inputs': {
                      'experiment_id': experiment.experiment_id
                  }
              })
          )
          
          if response.status_code == 204:
              print('Workflow dispatched successfully.')
          else:
              print(f'Failed to dispatch workflow. Status code: {response.status_code} Response: {response.text}')
              raise RuntimeError

      - name: Create issue with PR title and description
        shell: python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          import requests
          import json

          issue_title = "${{ github.event.pull_request.title }}"
          issue_body = "Related PR: #${{ github.event.pull_request.number }}\n\n${{ github.event.pull_request.body }}"

          url = f"https://api.github.com/repos/${{ github.repository }}/issues"
          payload = json.dumps({
            "title": issue_title,
            "body": issue_body,
          })
          headers = {
            "Authorization": "Bearer ${GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json",
          }

          response = requests.post(url, data=payload, headers=headers)

          if response.status_code == 201:
              print("Issue created successfully.")
          else:
              print(f"Failed to create issue. Status code: {response.status_code} Response: {response.text}")
              raise RuntimeError
        


