name: "Text Classification: Test"

on:
  workflow_dispatch:
  pull_request:

env:
  AWS_REGION: eu-south-1

jobs:
  test-text-classification:
    name: Test text classification pipelines
    timeout-minutes: 1500
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/digital-defiance/sentiment-analysis-pipeline:main
      options: --user root
      env:
        RUST_BACKTRACE: "full"
        LIBTORCH_USE_PYTORCH: "1"
        LLMVC_ENVIRONMENT: "development"
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URL }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }} 
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }} 

    steps:
      # stuff to be moved to the production image
      - run: pip install psycopg2-binary # required for mlflow to talk to postgres
      - run: pip install mlflow
      - run: pip install prefect-shell

      - name: Find and set torch lib path
        run: |
          SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
          TORCH_LIB_PATH="${SITE_PACKAGES}/torch/lib"
          echo "LD_LIBRARY_PATH=$TORCH_LIB_PATH" >> $GITHUB_ENV
      - run: pip install pytest
      - name: Login to prefect
        run: yes | prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace 'digital-defiance/default'
      
      - run: pytest pipelines/text_classification/datagen.py -vvv
      
